name: Metrics
on:
  schedule: [{cron: "0 2 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: adnanegrb
          template: classic
          base: activity, repositories
          base_indepth: yes
          base_hireable: no

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 8

          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 20

          config_timezone: Europe/Paris
          config_order: base.header, isocalendar, languages, topics, base.activity
